server:
  port: 8080
spring:
  profiles:
    active: ${SPRING_PROFILE}
  application:
    name: springrealm
  cache:
    type: redis
  datasource:
    url: jdbc:postgresql://localhost:5432/springrealm
    username: docker
    password: docker
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: false
    database: postgresql
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url: jdbc:postgresql://localhost:5533/springrealm
    clean-disabled: true
    user: docker
    password: docker
    baseline-on-migrate: true
    enabled: true
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method